---
title: "10_Mol16S-diversity"
date: "2024-03-07"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,         # Display code chunks
  eval = TRUE,        # Evaluate code chunks
  warning = FALSE,     # Hide warnings
  message = FALSE,     # Hide messages
  fig.width = 10,       # Set plot width in inches
  fig.height = 6,      # Set plot height in inches
  fig.align = "center" # Align plots to the center
)
```

read data into R
note: I first had to convert the taxonomy table from text into csv for this to work
```{r}
MOL <- read.csv("/Users/hailaschultz/Dropbox/Schultz_Dissertation/Data_Analysis/Schultz_dissertation-2/data/Barcode_2018/Mol16S/Mol16S_ASVs_counts_mergedOnTaxonomy.tsv", sep = "\t")

MOL_tax <- read.csv("/Users/hailaschultz/Dropbox/Schultz_Dissertation/Data_Analysis/Schultz_dissertation-2/data/Barcode_2018/Mol16S/Mol16S_Tax_Assignment.csv")
```

add taxonomy assignments to COI dataframe
```{r}
#rename column
MOL<-MOL %>% 
  rename(
    ASV = x,
    )

MOL <- merge(MOL_tax,MOL, by="ASV", all.x=FALSE)
```

Convert to present (1) vs absent (0)
```{r}
#remove non-species rows
MOL_complete<- MOL[complete.cases(MOL), ]
#remove non-zooplankton taxa
unique(MOL_complete$Phylum)
MOL_complete <- droplevels(MOL_complete[!MOL_complete$Phylum == 'Chlorophyta',])
MOL_complete <- droplevels(MOL_complete[!MOL_complete$Phylum == 'Bacillariophyta',])

MOL_pa<-MOL_complete %>%
  mutate(across(where(is.numeric), ~ifelse(.x >0, 1, 0)))

```


wide to long format
```{r}
#remove exces columns
MOL_pa <- MOL_pa[ -c(2,5:8,10,16,18,21,22,24,26) ]
MOL_pa<-melt(MOL_pa, id.vars=c("Phylum", "Class","ASV"))
```

summarize by phylum
```{r}
MOL_pa_sum<-MOL_pa %>%
  group_by(Phylum, variable) %>%
  summarise(
    ASVs = sum(value))
```

make bar graph
```{r}
MOL_diversity<-ggplot(MOL_pa_sum, aes(x = variable, y = ASVs, fill = Phylum)) +
  geom_bar(stat = "identity") +
  labs(title = "Mol16S all species",
       x = "Station",
       y = "number of species") +
  theme_minimal()+
  scale_x_discrete(guide = guide_axis(angle = 90)) 
MOL_diversity
```

save plot
```{r, eval=FALSE}
setwd("/Users/hailaschultz/Dropbox/Schultz_Dissertation/Data_Analysis/Schultz_dissertation-2/figures")
ggsave(filename = "MOL_diversity.png", plot = MOL_diversity, width = 10, height = 8, device='png', dpi=700)
```